from twilio.rest import Client
from twilio.twiml.voice_response import VoiceResponse, Say

account_sid = 'AC7373c0567a71f78536e37bb00440c1be'
auth_token = 'af435efdcabfe312e087585cc63a069b'

client = Client(account_sid, auth_token)
response = VoiceResponse()

call = client.calls.create(
                        url='https://handler.twilio.com/twiml/EH575cfb9a61dd6ddae3db50816a7b446b',
                        to='+14794306900',
                        from_='+14792084105'
                    )

print(call.sid)

message = client.messages.create(
                        body='A truck carrying your shipment No. 1459323 has been involved in an accident on Razorback Road, Fayetteville, AR and is expected to cause a two day delay. This message was automatically generated by Crash Correspondance.',               
                        to='+14795959244',
                        from_='+14792084105'
)

print(message)