from twilio.rest import Client
from firebase import firebase

file = open('api_key.txt', 'r')
lines = [line for line in file.readlines()]
file.close()

firebase = firebase.FirebaseApplication(lines[0], None)

while True:
  result = firebase.get('/truck_status', None)

  print (result)

  account_sid = lines[1]
  auth_token = lines[2]
  client = Client(account_sid, auth_token)

  if result == 1: 
    
    firebase.put('/', 'truck_status', 0)
    call = client.calls.create(
                            url=lines[6],
                            to=lines[3],
                            from_=lines[5]
                        )

    print('success')

    message = client.messages.create(
                            body='A truck carrying your shipment No. 1459323 has been involved in an accident on Razorback Road, Fayetteville, AR and is expected to cause a 2 day delay. This message was automatically generated by Crash Correspondence.',               
                            to=lines[4],
                            from_=lines[5]
    )
    
    print(message)
    
    break

firebase.put('/', 'truck_status', 0)